model: ${oc.env:MODEL_PATH}
backend: ${oc.env:QWEN_ASR_BACKEND}
context: ${oc.env:QWEN_ASR_CONTEXT}
server_port: ${oc.env:QWEN_ASR_SERVER_PORT}

generation:
  max_new_tokens: ${oc.env:QWEN_ASR_MAX_NEW_TOKENS}

device: ${oc.env:QWEN_ASR_DEVICE}

vllm: null
transformers: null
