model: ${oc.env:MODEL_PATH}
backend: vllm
context: ${oc.env:QWEN_ASR_CONTEXT,""}
server_port: ${oc.env:QWEN_ASR_SERVER_PORT,50051}

generation:
  max_new_tokens: ${oc.env:QWEN_ASR_MAX_NEW_TOKENS,4096}

device: ${oc.env:QWEN_ASR_DEVICE,cuda}

vllm:
  gpu_memory_utilization: ${oc.env:QWEN_ASR_VLLM_GPU_MEMORY_UTILIZATION,0.8}
  max_model_len: ${oc.env:QWEN_ASR_VLLM_MAX_MODEL_LEN,4096}
  enforce_eager: ${oc.env:QWEN_ASR_VLLM_ENFORCE_EAGER,false}

transformers: null
